version: 2.1

orbs:
  docker: circleci/docker@2.1.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.15.0

jobs:
  # 1. Install Packages
  install:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  # 2. Run Tests
  test:
    executor: node-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: npm run test

  # 3. Build and Deploy to Docker Hub
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Build Docker Image
          command: |
            docker build \
              --file=./Dockerfile \
              --tag=docker.io/$DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest \
              .
      - run:
          name: Push to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin docker.io
            docker push docker.io/$DOCKERHUB_USERNAME/$DOCKER_IMAGE_NAME:latest

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - build-and-deploy:
          requires:
            - test
          filters:
            branches:
              only: main